### ISSUE TITLE
How to use the i18next t() function outside of handler functions?

### ISSUE THREAD

**Issue by marcusx** [alexa-samples/skill-sample-nodejs-quiz-game#31]
If I want to use the i18next t() function outside of a handler in one of the helper functions what is the best way to achieve that?

e.g:
I register language strings in the alexa object like so:
```
exports.handler = (event, context) => {
  const alexa = Alexa.handler(event, context);
  alexa.appId = APP_ID;

  alexa.resources = languageStrings; // Add some language strings here.

  alexa.registerHandlers(handlers, startHandlers, quizHandlers);
  alexa.execute();
};
```

But in `getSpeachDescription` I have no access to this.t(). What is the recommended way to use the language strings there?
see: 
https://github.com/alexa/skill-sample-nodejs-quiz-game/blob/bfbcbfe092fa2ff10f5bdcd8eeff66902ac1a027/lambda/custom/index.js#L14

* Init my own i18next object with the same resources?
* Use a `.call` statement like `getSpeachDescription.call(this);`
* Use the alexa object inside the helper function?
* Other / better method?

**Comment by franklin-lobb** [comment]
I think the proper code method is to use `.call`, however the approach which would require the least amount code might be to pass the alexa object to the helper function.

In the samples which use the new SDK, we demonstrate using a request attribute for passing the i18next object, and the use of strings with %s so that you can have i18next do the substitution rather than have a function to build it.  Perhaps using a similar approach and not using a function at all will do the trick.
